import type { Metadata } from "next";
import "./globals.css";
import { jetbrains } from "./fonts";
import { Header } from "@/components/sections/Header";
import { Sidebar } from "@/components/Sidebar";
import { Footer } from "@/components/sections/Footer";

export const metadata: Metadata = {
  title: "Fuad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={jetbrains.className}
    >
      <body>
        <Header />
        <Sidebar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
