import type { Metadata } from "next";
import "./globals.css";
import { jetbrains } from "./fonts";
import { Header } from "@/components/sections/Header";
import { Sidebar } from "@/components/Sidebar";
import { Footer } from "@/components/sections/Footer";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
  title: "Fuad",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params: { locale } }: { children: React.ReactNode; params: { locale: string } }) {
  if (!routing.locales.includes(locale as "en" | "az" | "ru")) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      className={jetbrains.className}
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <Header />
          <Sidebar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
